/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolarCalculatorRouteImport } from './routes/solar-calculator'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as ComparisonsRouteImport } from './routes/comparisons'
import { Route as IndexRouteImport } from './routes/index'

const SolarCalculatorRoute = SolarCalculatorRouteImport.update({
  id: '/solar-calculator',
  path: '/solar-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonsRoute = ComparisonsRouteImport.update({
  id: '/comparisons',
  path: '/comparisons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparisons': typeof ComparisonsRoute
  '/guides': typeof GuidesRoute
  '/solar-calculator': typeof SolarCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparisons': typeof ComparisonsRoute
  '/guides': typeof GuidesRoute
  '/solar-calculator': typeof SolarCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparisons': typeof ComparisonsRoute
  '/guides': typeof GuidesRoute
  '/solar-calculator': typeof SolarCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comparisons' | '/guides' | '/solar-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comparisons' | '/guides' | '/solar-calculator'
  id: '__root__' | '/' | '/comparisons' | '/guides' | '/solar-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparisonsRoute: typeof ComparisonsRoute
  GuidesRoute: typeof GuidesRoute
  SolarCalculatorRoute: typeof SolarCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solar-calculator': {
      id: '/solar-calculator'
      path: '/solar-calculator'
      fullPath: '/solar-calculator'
      preLoaderRoute: typeof SolarCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparisons': {
      id: '/comparisons'
      path: '/comparisons'
      fullPath: '/comparisons'
      preLoaderRoute: typeof ComparisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparisonsRoute: ComparisonsRoute,
  GuidesRoute: GuidesRoute,
  SolarCalculatorRoute: SolarCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
